### ISSUE TITLE
Remove from hoomd import * in unit tests

### ISSUE THREAD

**Issue by astatt** [mphowardlab/azplugins#33]
For consistency, we should change and check the hoomd import statements in the *.py files, e.g. ```from hoomd import *``` to ``` import hoomd``` and associated necessary changes. This is not urgent by any means.

**Comment by mphoward** [comment]
Yes, this is a good idea. The first pass solution would be to convert all the commands, prepending `hoomd` as needed.

I also would like to simplify the unit tests #34, which could make this easier. We can decide what order to do that in.
