### ISSUE TITLE
Migrate to HOOMD 4.0

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/azplugins#44]
A beta release of HOOMD 3.0 is now available, and we should start the process of migrating our code.

As discussed with @astatt, PR #40 will be the last feature added for HOOMD 2.9, and it will be included in our last 0.x minor release. From there, all new features should target HOOMD 3.0, and we will begin the process of supporting the new API. We will keep a v0.11 (or hoomd-29? name TBD) branch open to support bug fixes for old code for so long as it is practical.

Steps that need to be taken:

- [ ] Update CMake to use first-class CUDA support and package searching.
- [ ] Require C++14 standard in CMake.
- [ ] Update defines to use "HIP" syntax and/or use hipper. The GPU support is now very confusing.
- [ ] See what compiles (or doesn't), and fix anything obvious.
- [ ] Try pair potentials as hopefully the easiest thing to migrate.

HOOMD now uses `pytest` rather than `unittest` for python-level testing. We could consider using some of their test fixtures, since they should be installed alongside the code, or we can stick with our existing unit tests. Either way, I do think we should try to consolidate tests where possible (#34).

We should also hit the goal of fully hosting documentation and finishing packaging for this for the official 1.0 release. I'm sure more things will pop up, and we can add to this list as needed.

**Comment by jamie-arcc** [comment]
Is this ever going to happen?  HOOMD has already progressed to 3.5.0 and there are a lot of improvements, including to the build process

**Comment by mphoward** [comment]
Yes, we are still planning to do this, but there is considerable effort needed to do it. HOOMD v3 implemented multiple API-breaking changes that we need to accommodate. I agree that the improved build process is a major benefit.

**Comment by astatt** [comment]
Bug in hoomd with bonds in external plugins is [reported](https://github.com/glotzerlab/hoomd-blue/issues/1591) and fix pull [request](https://github.com/glotzerlab/hoomd-blue/pull/1594) opened.

**Comment by mphoward** [comment]
Only a few years longer than planned… 🙂
