### ISSUE TITLE
Make azplugins available on conda forge?

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/azplugins#45]
HOOMD is available on conda forge and users seem to use / install it that way. Should we look into supplying azplugins on conda forge as well for convenience?

```bash
conda install -c conda-forge azplugins
```

**Comment by astatt** [comment]
I have no sense of how much effort it is going to be, but for users who do not intend to develop any features this would be extremely convenient, and could potentially give us a broader user base. 

Let's check how difficult it would be and how much effort it will be to maintain it. We should offer two versions, last one to support ``hoomd-2.X`` (e.g. the minor bug-fix +support branch) and then the new ``hoomd-3.0`` one.  Is there a way to include a circleci + docker test for this as well?

**Comment by mphoward** [comment]
I think it is not too bad to maintain after you get it setup at first. You propose a recipe on conda forge, which then gets you a conda feedstock repository, and then we just need to remember to bump this as we add new versions. I will look into it since I agree it would be very convenient.

**Comment by mphoward** [comment]
It's pretty easy to build plugins, and I'm not planning to do this unless Josh supplies an easy template / mechanism for it.
