### ISSUE TITLE
Import mpcd by default?

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/azplugins#46]
Should we try to import the mpcd module (like we do for `_mpcd` from `hoomd`) so that it is available in the same namespace as other modules when azplugins is built with MPCD?

**Comment by astatt** [comment]
I would say yes once we go to azplugins-v1 and hoomd4. This is easier for the users I think.

**Comment by mphoward** [comment]
I agree. We should be able to add conditional compilation of this at the CMake level, and conditional import at the Python level.

**Comment by mphoward** [comment]
There is no use of MPCD in azplugins currently. The first PR to introduce code that does can resolve this.
