### ISSUE TITLE
Switch unit tests to GitHub Actions

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/azplugins#54]
CircleCI is a pain and GitHub Actions is clean. We should migrate the tests to this platform, and simplify the configurations we test.

**Comment by astatt** [comment]
Can/Should go with Issue #34

**Comment by mphoward** [comment]
We currently run alot of different builds on every commit, which I previously managed to keep efficient by stuffing multiple versions of HOOMD into one Docker image. These images are time consuming to compile and maintain though, so when we make this switch, I propose that we start using the glotzerlab Docker images and build HOOMD on the fly. We might be able to do this in a way where we cache the compiled HOOMD as an artifact on github, which we can then reload. Here's what the HOOMD test workflow looks like:

https://github.com/glotzerlab/hoomd-blue/blob/master/.github/workflows/test.yml

Alternatively, we need a script that produces the testing Dockerfiles, and we need to pare down the list of things we test.

**Comment by mphoward** [comment]
Closed via #57
