### ISSUE TITLE
Revise documentation

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/azplugins#56]
This is a new issue (building from #1) to track edits and revisions that need to be made to the documentation:

- [ ] Main index should either embed the readme or have some text included
- [ ] Installation instructions need to be condensed (borrow from readme). The tutorial text that is there is for verifying an installation.
- [ ] Add module level documentation for pretty much all modules.
- [ ] Add overview text for Potentials index page (in addition to toc).
- [ ] Math equations are rather broken, try to clean them up.
- [ ] Check for use of single vs. double ticks throughout.
- [ ] Collapse release notes table of contents by adding a `v0.x` header. This will be useful when we finally get to `v1.0.0`.
- [ ] Check tutorials for typos. At least one of them is misnumbered since there are two "Tutorial 3". I would propose that we actually get these separated out into individual directories (do not include two related notebooks in one folder) to make it easier to count them.
- [ ] Proofread all modules.
- [ ] Remove test version of HOOMD from README. It is easy to let it get out of date.
- [ ] Add badge to README for RTD.
- [ ] Check for missing `:members:` documentation where it's needed.

Anyone should feel free to work on these. Please document on this thread if you complete an item, especially if you proofread a module.

**Comment by astatt** [comment]
Do you want to address these points in a separate branch or as hotfixes?

**Comment by mphoward** [comment]
They can be addressed whenever we feel like it, in any size chunk, and merged immediately to `main`. (I am going to remove the `develop` branch after we merge the last open PRs.)

**Comment by mphoward** [comment]
The documentation will need to be redone when v1 is ready.

**Comment by mphoward** [comment]
Documentation was rewritten for v1. Any changes and additions are welcome in new PRs.
