### ISSUE TITLE
test_mpcd_velocity_compute.py incompatible with internal build

### ISSUE THREAD

**Issue by bcjeong1616** [mphowardlab/azplugins#71]
When building Azplugins internal to Hoomd 2.9.6, 2 tests fail at import due to an import structure that assumes Azplugins is built externally:

Traceback (most recent call last):
  File "/home/bj21/programs/hoomd-blue/hoomd/azplugins/test-py/test_mpcd_velocity_compute.py", line 13, in <module>
    import azplugins.mpcd
ModuleNotFoundError: No module named 'azplugins'

These tests are found in azplugins/test-py/test_mpcd_velocity_compute.py
I've found these tests can be run by modifying lines 9-13 in the aforementioned script:
```
try:
    from hoomd import azplugins
except ImportError:
    import azplugins
import azplugins.mpcd
```

To this:
```
try:
    from hoomd import azplugins
    import hoomd.azplugins.mpcd
except ImportError:
    import azplugins
    import azplugins.mpcd
```

**Comment by mphoward** [comment]
Thanks for reporting this! It is likely caused by changes in relative imports in different Python versions. We will address this whenever we get around to porting this plugin to HOOMD 4.

**Comment by mphoward** [comment]
This will no longer be an issue in v1.
